services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
    ports:
      - "3307:3306"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    restart: always